name: mauzoApp
description: A new Flutter project.
version: 1.0.0+1
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  cached_network_image: ^3.2.1
  carousel_slider: ^4.0.0
  chips_choice_null_safety: any
  connectivity_plus: ^2.3.6
  date_picker_timeline: ^1.2.3
  dotted_decoration: ^2.0.0
  flutter_launcher_icons: any
  flutter:
    sdk: flutter
  flutter_readmore: ^0.0.2
  flutter_svg: ^0.22.0
  flutter_switch: ^0.3.2
  get: ^4.6.5
  google_sign_in: ^5.0.7
  images_picker: ^1.2.11
  intl: ^0.17.0
  animate_do: ^3.0.2
  video_player: ^2.4.6
  google_maps_flutter: ^2.1.12
  permission_handler: ^10.0.0
  pin_code_fields: 8.0.1
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2
  readmore: ^2.1.0
  sms_autofill: ^2.0.0
  get_storage: ^2.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/thumbnail.png"
flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
  fonts:
    - family: Noto Sans JP
      fonts:
        - asset: assets/fonts/NotoSansJPMedium.otf
          weight: 500
        - asset: assets/fonts/NotoSansJPBold.otf
          weight: 700
        - asset: assets/fonts/NotoSansJPRegular.otf
          weight: 400
    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/PlusJakartaSansBold.ttf
          weight: 700
        - asset: assets/fonts/PlusJakartaSansSemiBold.ttf
          weight: 600
